### ISSUE TITLE
input mongo much faster than mubsub get data out issue

### ISSUE THREAD

**Issue by yuz11** [scttnlsn/mubsub#48]
Is it possible that writing to fast into mongo and mubsub channel get data out and handle not fast enough.Then at some point the cursor of capped collection become invalid,the channel then become invalid,data flow stops?
I read the code in lib/channel.js and assume it should hanpped. Please tell me about it if I'm wrong

**Comment by scttnlsn** [comment]
Not sure if this is an issue.  Have you run into it?  If so, do you have a way to replicate the issue?

**Comment by yuz11** [comment]
Haven't run into it yet,just concern about the possibility as I add a feature of speed limit in my version(have to deal with the situation that consumer do not have the ability to handle whole data flow input to mongo),it might run into it.

**Comment by omakoleg** [comment]
When collection will be full, it will just overwrite it from beginning
from mongo docs:
"Capped collections work in a way similar to circular buffers: once a collection fills its allocated space, it makes room for new documents by overwriting the oldest documents in the collection."
You could set collection size to fit in all data for some predefined time if no subscribers will be defined

Readable cursors will not fail because `numberOfRetries: Number.MAX_VALUE` will be quire hard to reach. ps. it will start count each time when no new elements found

**Comment by yuz11** [comment]
@omakoleg thanks for the comment.You mean the readable cursors is about the offset of the mongo storage,so when data renew,the cursor will point to new data in the same offset?
However I might ran into this situation in my project.And I just call the listen() method to restart subscribe.Just a work around.

**Comment by omakoleg** [comment]
Didnt clearly understand situation You described.

Cursor always return new data as soon as it is available in collection. Then of course it will move to the end of collection and wait for another data came in.
